const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
let history=JSON.parse(localStorage.getItem("espynos_history")||"[]");
function nav(target){$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.target===target));$$(".panel").forEach(x=>x.classList.toggle("active-panel",x.id===target));window.scrollTo({top:0,behavior:"smooth"})}
$$(".nav").forEach(b=>b.onclick=()=>nav(b.dataset.target));
$("#newChat").onclick=()=>{history=[];localStorage.removeItem("espynos_history");renderMessages()};
function renderMessages(){const box=$("#messages");box.innerHTML="";if(!history.length){box.innerHTML=`<div class="welcome"><div class="welcome-icon">✦</div><h3>How can I help?</h3><p>Ask ESPYNOS-AI anything, request code, research a topic, or create media.</p><div class="suggestions"><button>Build a website</button><button>Explain quantum computing</button><button>Search today's technology news</button></div></div>`;bindSuggestions();return}history.forEach(m=>{const d=document.createElement("div");d.className="msg "+(m.role==="user"?"user":"ai");d.textContent=m.text;box.appendChild(d)});box.scrollTop=box.scrollHeight}
function bindSuggestions(){$$(".suggestions button").forEach(b=>b.onclick=()=>{$("#prompt").value=b.textContent;$("#chatForm").requestSubmit()})}
async function chat(text){const box=$("#messages");const u=document.createElement("div");u.className="msg user";u.textContent=text;box.appendChild(u);const a=document.createElement("div");a.className="msg ai";a.textContent="ESPYNOS is thinking…";box.appendChild(a);box.scrollTop=box.scrollHeight;
history.push({role:"user",text});try{const r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,history,model:$("#model").value})});const data=await r.json();a.textContent=data.reply||data.error||"No response.";history.push({role:"assistant",text:a.textContent});localStorage.setItem("espynos_history",JSON.stringify(history))}catch(e){a.textContent="Connection error. Check the Render service and API configuration."}}
$("#chatForm").onsubmit=e=>{e.preventDefault();const t=$("#prompt").value.trim();if(t){$("#prompt").value="";chat(t)}};
$("#attachBtn").onclick=()=>$("#fileInput").click();$("#fileInput").onchange=e=>{if(e.target.files.length){$("#prompt").value+=` [Attached ${e.target.files.length} file(s)]`}};
let recognition;$("#micBtn").onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Voice input is not supported by this browser.");return}recognition=new SR();recognition.lang="en-US";recognition.onresult=e=>$("#prompt").value+=e.results[0][0].transcript;recognition.start()};
$("#searchForm").onsubmit=async e=>{e.preventDefault();const q=$("#searchInput").value.trim();if(!q)return;$("#searchResults").innerHTML="<p>Searching DuckDuckGo…</p>";try{const r=await fetch("/api/search?q="+encodeURIComponent(q));const d=await r.json();const arr=d.results||[];$("#searchResults").innerHTML=arr.length?arr.map(x=>`<article class="result"><a href="${x.url}" target="_blank" rel="noopener">${x.title||x.url}</a><p>${x.snippet||""}</p></article>`).join(""):"<p>No instant results found. Try a more specific query.</p>"}catch(e){$("#searchResults").innerHTML="<p>Search service unavailable.</p>"}};
$("#runCode").onclick=()=>{$("#preview").srcdoc=$("#codeInput").value};
$$(".tool").forEach(b=>b.onclick=async()=>{if(b.id==="voiceBtn"){return startVoice()}const task=b.dataset.code;nav("chat");$("#prompt").value=task==="html"?"Create a modern HTML landing page.":task==="js"?"Write JavaScript for a responsive interactive app.":task==="python"?"Write clean Python for this task: ":"Analyze and improve my code.";$("#chatForm").requestSubmit()});
$("#imageBtn").onclick=()=>{const p=$("#imagePrompt").value.trim();if(!p)return;const url="/api/image?prompt="+encodeURIComponent(p);$("#imageOut").innerHTML=`<img class="generated-img" src="${url}" alt="Generated image" loading="lazy">`};
$("#videoBtn").onclick=async()=>{const p=$("#videoPrompt").value.trim();if(!p)return;$("#videoOut").textContent="Submitting video generation job…";try{const r=await fetch("/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:p,ratio:$("#ratio").value,duration:$("#duration").value})});const d=await r.json();$("#videoOut").textContent=d.message||d.error||"Video provider is not configured yet."}catch(e){$("#videoOut").textContent="Video job service unavailable."}};
function startVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){alert("Voice recording is not supported here.");return}const r=new SR();r.onstart=()=>$("#voiceOut").textContent="Listening…";r.onresult=e=>$("#voiceOut").textContent=e.results[0][0].transcript;r.onend=()=>$("#voiceOut").textContent+="  • Voice capture finished.";r.start()}
$("#settingsBtn").onclick=()=>$("#settings").classList.add("open");$("#closeSettings").onclick=()=>$("#settings").classList.remove("open");$("#settings").onclick=e=>{if(e.target.id==="settings")$("#settings").classList.remove("open")};
$("#glow").oninput=e=>document.documentElement.style.setProperty("--glow",e.target.value);$("#themeBtn").onclick=()=>document.body.classList.toggle("less-glow");
bindSuggestions();renderMessages();
