const $=s=>document.querySelector(s),$$=s=>document.querySelectorAll(s);let hist=JSON.parse(localStorage.getItem("espynos_v3")||"[]");
function nav(p){$$(".nav").forEach(x=>x.classList.toggle("active",x.dataset.page===p));$$(".panel").forEach(x=>x.classList.toggle("active",x.id===p));scrollTo({top:0,behavior:"smooth"})}$$(".nav").forEach(x=>x.onclick=()=>nav(x.dataset.page));
function render(){const m=$("#messages");m.innerHTML="";if(!hist.length){m.innerHTML='<div class="welcome">✦<h3>ESPYNOS is online</h3><p>Ask anything. Build anything. Explore anything.</p><div><button class="suggest">Build a futuristic website</button> <button class="suggest">Explain AI to me</button></div></div>';$$(".suggest").forEach(b=>b.onclick=()=>{$("#prompt").value=b.textContent;$("#form").requestSubmit()});return}hist.forEach(x=>{let d=document.createElement("div");d.className="msg "+(x.role==="user"?"user":"ai");d.textContent=x.text;m.appendChild(d)});m.scrollTop=m.scrollHeight}
async function ask(t){let m=$("#messages"),u=document.createElement("div"),a=document.createElement("div");u.className="msg user";u.textContent=t;a.className="msg ai";a.textContent="ESPYNOS is processing…";m.append(u,a);hist.push({role:"user",text:t});try{let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:t,history:hist,model:$("#model").value})}),d=await r.json();a.textContent=d.reply||d.error||"No response";hist.push({role:"assistant",text:a.textContent});localStorage.setItem("espynos_v3",JSON.stringify(hist))}catch(e){a.textContent="AI connection unavailable. Check the Render service/API key."}m.scrollTop=m.scrollHeight}
$("#form").onsubmit=e=>{e.preventDefault();let t=$("#prompt").value.trim();if(t){$("#prompt").value="";ask(t)}};$("#new").onclick=()=>{hist=[];localStorage.removeItem("espynos_v3");render()};$("#attach").onclick=()=>$("#files").click();$("#files").onchange=e=>{$("#prompt").value+=` [${e.target.files.length} file(s) attached]`};
$("#run").onclick=()=>$("#preview").srcdoc=$("#editor").value;
$("#searchForm").onsubmit=async e=>{e.preventDefault();let q=$("#query").value.trim();if(!q)return;$("#results").innerHTML="<p>Searching…</p>";try{let r=await fetch("/api/search?q="+encodeURIComponent(q)),d=await r.json();$("#results").innerHTML=(d.results||[]).map(x=>`<div class="result"><a href="${x.url}" target="_blank">${x.title||x.url}</a><p>${x.snippet||""}</p></div>`).join("")||"<p>No instant results.</p>"}catch(e){$("#results").innerHTML="<p>Search unavailable.</p>"}};
$("#image").onclick=()=>{let p=$("#imagePrompt").value.trim();if(p)$("#imageOut").innerHTML=`<img src="/api/image?prompt=${encodeURIComponent(p)}">`};
$("#video").onclick=async()=>{let p=$("#videoPrompt").value.trim();if(!p)return;let r=await fetch("/api/video",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt:p})}),d=await r.json();$("#videoOut").textContent=d.message||"Video provider not configured."};
$("#voice").onclick=()=>{let R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R)return alert("Voice input is not supported in this browser.");let r=new R();$("#voiceOut").textContent="Listening…";r.onresult=e=>$("#prompt").value+=e.results[0][0].transcript;r.onend=()=>$("#voiceOut").textContent="Voice capture complete.";r.start()};
$("#settings").onclick=()=>$("#modal").classList.add("open");$("#close").onclick=()=>$("#modal").classList.remove("open");render();